export const ButtonStyle = {
    borderRadius: '20px',
    background: '#FFC700',
    color: '#000',
    textTransform: 'none',
    fontSize: '18px',
    fontWeight: 500,
    '&:hover': {background: '#FFC700'},
    width: '244px',
    minHeight: '64px',
    paddingLeft: '47px',
    paddingRight: '47px',
    lineHeight: 'normal',
    textWrap: 'nowrap',
};
